version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: ./master/gradlew -c ./master/settings.gradle dependencies
      - run: ./master/gradlew -c ./master/settings.gradle :bitvector:test
      - run: ./master/gradlew -c ./master/settings.gradle :trie:test

